version: '3.9'

services:
    worker-example:
        image: worker-example
        container_name: worker-example
        restart: always
        network_mode: host
        build:
            context: '../../'
            dockerfile: 'Dockerfile_worker'
            args:
                SOURCE_FOLDER: 'service_event_store'
        command: python worker.py service_event_store