version: '3.9'

services:
    worker-event:
        image: worker-event
        deploy:
            mode: replicated
            replicas: 2
        restart: always
        network_mode: host
        build:
            context: '../../'
            dockerfile: 'Dockerfile_worker'
            args:
                SOURCE_FOLDER: 'service_event_store'
        command: python worker.py service_event_store.worker
    
    worker-example-created:
        image: worker-example-created
        deploy:
            mode: replicated
            replicas: 1
        restart: always
        network_mode: host
        build:
            context: '../../'
            dockerfile: 'Dockerfile_worker'
            args:
                SOURCE_FOLDER: 'service_example'
        command: python worker.py service_example.worker_created

    worker-example-delete:
        image: worker-example-delete
        deploy:
            mode: replicated
            replicas: 1
        restart: always
        network_mode: host
        build:
            context: '../../'
            dockerfile: 'Dockerfile_worker'
            args:
                SOURCE_FOLDER: 'service_example'
        command: python worker.py service_example.worker_delete_requested