### Site metadata ###

site_name: MkDocs Quickstart
site_description: Starter template for a MkDocs docs site on GH Pages - including CI
site_url: https://britto-andre.github.io/scaffold_python_services_project/docs/

repo_url: https://github.com/britto-andre/scaffold_python_services_project
# edit_uri: edit/master/docs/docs

### Build settings ###

theme: readthedocs

nav:
  - Home: index.md
  - About MkDocs: about-mkdocs.md