site_name: Documentation
site_description: 'Documentation of the scaffold python service project'
site_author: 'André Britto'
site_url: https://britto-andre.github.io/scaffold_python_services_project

docs_dir: docs/

# repo_name: 'britto-andre/scaffold_python_services_project'
repo_url: 'https://github.com/britto-andre/scaffold_python_services_project'

nav:
    - Home: index.md

theme:
  name: 'mkdocs'