version: '3.9'

volumes:
    keycloak-mysql-data:
        driver: local
    keycloak-data: {}

services:
    keycloak-mariadb:
        image: mariadb
        container_name: keycloak-mariadb
        restart: always
        volumes:
            - keycloak-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: password

    keycloak:
        image: jboss/keycloak
        container_name: keycloak
        environment:
            DB_VENDOR: mariadb
            DB_ADDR: keycloak-mariadb
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            KEYCLOAK_STATISTICS: all
            PROXY_ADDRESS_FORWARDING: "true"
            # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
            #JDBC_PARAMS: "connectTimeout=30000"
        volumes:
            - keycloak-data:/data
            - ./providers:/opt/jboss/keycloak/providers
        ports: [8080:8080]
        depends_on:
            - keycloak-mariadb