version: '3.9'

# networks:
#     infra-network:
#         name: infra_network

volumes:
    prometheus-data: {}
    grafana-data: {}

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./prometheus-config/:/prometheus-config
            - prometheus-data:/prometheus
        command:
            - '--config.file=/prometheus-config/prometheus.yml'
        # networks: [infra-network]
        ports:
            - 9090:9090
        restart: always

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
        - grafana-data:/var/lib/grafana
        # networks: [infra-network]
        ports:
        - 3000:3000
        depends_on:
        - prometheus