version: '3.9'

services:
    api-example:
        image: api-example
        container_name: api-example
        restart: always
        ports:
            - "8000:8000"
        environment:
            event_sender: "api-example"
            mongo_uri: "mongodb://host.docker.internal:27017/"
            amqp_uri: "amqp://guest:guest@host.docker.internal/"
        build:
            context: '../../'
            dockerfile: 'Dockerfile_api'
            args:
                SOURCE_FOLDER: 'service_example'
        command: uvicorn src.app.service_example.api:app --host 0.0.0.0 --port 8000